# GitLab pages deployment
pages:
  stage: deploy
  script:
  - echo 'Nothing to do...'
  artifacts:
    paths:
    - public
  only:
  - master

# Auto push repo to GitHub
# Adapted from https://docs.gitlab.com/ce/ci/yaml/README.html
job:
  stage: deploy
  script:
    - echo "Setting up SSH for sync to GitHub"

    # Install ssh-agent if not already installed, it is required by Docker.
    # (change apt-get to yum if you use an RPM-based image)
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'

    # Run ssh-agent (inside the build environment)
    - eval $(ssh-agent -s)

    # Create the SSH directory and give it the right permissions
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh

    # Put GitHub on known hosts list.
    - 'ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts'

    ## Add the SSH keys stored in the variables to the agent store
    ## We're using tr to fix line endings which makes ed25519 keys work
    ## without extra base64 encoding.
    ## https://gitlab.com/gitlab-examples/ssh-private-key/issues/1#note_48526556
    - echo "$SSH_GITHUB_PUSH_SYNC" | tr -d '\r' | ssh-add - > /dev/null

    # Run the git sync script.
    - bash sync.sh
